# Exercises for Section 3.1 Estimates and estimators

This notebook contains the solutions to the exercises
from [Section 3.1 Estimates and estimators]()
in the **No Bullshit Guide to Statistics**.

### Notebooks setup

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Simplified int and float __repr__
import numpy as np
np.set_printoptions(legacy='1.25')

In [3]:
# Pandas display options
pd.set_option("display.precision", 2)

In [4]:
# Figures setup
plt.clf()  # needed otherwise `sns.set_theme` doesn't work
sns.set_theme(
    context="paper",
    style="whitegrid",
    palette="colorblind",
)
%config InlineBackend.figure_format = "retina"

### Estimator functions defined in Section 3.1

In [5]:
def mean(sample):
    return sum(sample) / len(sample)

def var(sample):
    xbar = mean(sample)
    sumsqdevs = sum([(xi-xbar)**2 for xi in sample])
    return sumsqdevs / (len(sample)-1)

def std(sample):
    s2 = var(sample)
    return np.sqrt(s2)

def dmeans(xsample, ysample):
    dhat = mean(xsample) - mean(ysample)
    return dhat

## Exercises 1


### Exercise 3.1

Compute the sample mean from Batch 01 and Batch 04 of the kombucha dataset `datasets/kombucha.csv` .

In [6]:
kombucha = pd.read_csv("datasets/kombucha.csv")
ksample01 = kombucha[kombucha["batch"]==1]["volume"]

# compute the mean of Batch 1

In [8]:
ksample04 = kombucha[kombucha["batch"]==4]["volume"]

# compute the mean of Batch 4

### Exercise 3.2

Compute the sample variance from Batch 02 and Batch 08 of the kombucha dataset `datasets/kombucha.csv`.

In [10]:
kombucha = pd.read_csv("datasets/kombucha.csv")
ksample02 = ...  # select Batch 02 here...

# compute its variance

In [12]:
ksample08 = ... # select Batch 08 here... 

# compute its variance

### Exercise 3.3

Compute the difference between the means of the sleep `score`s 
for the doctors working in `rur`al and `urb`an locations
in the doctors dataset `datasets/doctors.csv`.

Hint: Use the code `doctors[doctors["loc"]=="rur"]` to select
the subset of the doctors working in a `rural` location.

In [14]:
doctors = pd.read_csv("datasets/doctors.csv")
scoresR = doctors[doctors["loc"]=="rur"]["score"]
scoresU = ... # select doctors from "urb" location here

# compute difference between scores

## Exercises 2


### Exercise 3.4

Generate $N=10000$ observations from the sampling distribution of the estimator `std` for samples of size $n=20$ from the population `rvK`  $= K \sim \mathcal{N}(1000,10)$ .
Plot a histogram.

In [16]:
from scipy.stats import norm
muK = 1000
sigmaK = 10
rvK = norm(muK, sigmaK)

# generate the sampling distribution of the standard deviation
from ministats import gen_sampling_dist
kstds20 = ...

In [17]:
# plot histogram of the sampling distribution `kstds20`
...

Ellipsis

### Exercise 3.5

Generate the sampling distributions of the estimator `mean` for samples of size $n=10$ , $n=30$ , and $n=100$ from the population `rvK`  $= K \sim \mathcal{N}(1000,10)$ .
Plot a histogram for each distribution.
Plot also the probability density function of the normal approximations
predicted by the central limit theorem for each case.

In [20]:
from scipy.stats import norm
muK = 1000
sigmaK = 10
rvK = norm(muK, sigmaK)

# simulations of Xbar for different sample sizes:
xbars10 = ... 
xbars30 = ... 
xbars100 = ...

In [22]:
# CASE n = 10

# Plot the histogram obtained from simulation
...

# Find the CLT approximation
seKbar10 = ...
rvKbarCLT10 = norm(..., ...)

# Plot the pdf of the CLT approximation
from ministats import plot_pdf
...

Ellipsis

In [24]:
# CASE n = 30

In [26]:
# CASE n = 100

### Exercise 3.6

Generate sampling distribution of the mean for samples of size $n=30$ from the standard uniform model `rvU`  $= U \sim \mathcal{U}(0,1)$ .
Plot a histogram.
Compare your result with Figure~ \ref{fig:sampling_dist_of_Ubar} on page \pageref{fig:sampling_dist_of_Ubar} .
Plot the prediction of the central limit theorem on the same axis.

In [28]:
from scipy.stats import uniform
rvU = uniform(0,1)

# the mean and standard deviation of the population are
muU = rvU.mean()
sigmaU = rvU.std()
muU, sigmaU

(0.5, 0.28867513459481287)

In [30]:
# simulations of Ubar for samples of size 30
ubars30 = ...

# Plot the histogram obtained from simulation
...  # hint: ax = sns.histplot(ubars30, stat="density")

# Find the CLT approximation
...

# Plot the pdf of the CLT approximation
from ministats import plot_pdf
...

Ellipsis

## Exercises 3


### Exercise 3.7

Use bootstrap estimation to obtain an approximation to the sampling distribution of the mean
from the sample of apple weights in the dataset `datasets/apples.csv` .
Based on your result,
what can you say about the unknown population mean $\mu_A$?
What is the standard error of your estimate?
State your answer as $\overline{\mathbf{a}} \pm \stderrhat{\overline{\mathbf{a}}}$ and interpret in words.

In [32]:
apples = pd.read_csv("datasets/apples.csv")
asample = apples["weight"]
apples.head(3)

   weight
0   205.0
1   182.0
2   192.0

In [33]:
from ministats import gen_boot_dist

abars_boot = ...

In [35]:
# compute mean and standard deviation of abars_boot

### Exercise 3.8

Compute bootstrap distribution for the sample mean from Batch 04 of the kombucha dataset,
and plot a histogram.
Do you think Batch 04 is a regular batch or an irregular batch of production?

In [37]:
kombucha = pd.read_csv("datasets/kombucha.csv")
ksample04 = kombucha[kombucha["batch"]==4]["volume"]
mean(ksample04)

1003.8335

## Exercises 4

### E3.9

Describe your uncertainty about the unknown population mean $\mu_A$ based on sample of apple weights from the dataset `datasets/apples.csv`:  
**a)** find an analytical formula in terms Student's $t$ -distribution,  
**b)** use bootstrap estimation,  
**c)** compare your answers from part a) and b) graphically.

In [39]:
apples = pd.read_csv("datasets/apples.csv")
asample = apples["weight"]
apples.head(3)

   weight
0   205.0
1   182.0
2   192.0

In [40]:
# a) Find the CLT approximation
from scipy.stats import t as tdist

n = asample.count()
df = ...
loc = ...
scale = ...
rvTAbar = tdist(df, loc=loc, scale=scale)

# Plot the pdf of the CLT approximation
...

Ellipsis

In [42]:
# b) obtain a bootstrap approximation
abars_boot = ...

## Exercises 5


### Exercise 3.10

Under regular operations,
the kombucha volume is described by the model `rvK`  $= K \sim \mathcal{N}(1000,10)$ .  
**a)** Plot the probability density function for the sampling distribution of the variance for samples of size $n=40$ from the population $K$ .  
**b)** Compute the sample variance of Batch 08 from the kombucha dataset.  
**c)** Compare the observed value in b) to the sampling distribution in a).
Does it look like this is a regular batch or irregular batch?

In [44]:
# a) Find the sampling distribution of the sample variance
from scipy.stats import chi2

n = ...
df = ...
scale = ...
rvS2 = chi2(df, loc=0, scale=scale)

# Plot the pdf of the CLT approximation
...

Ellipsis

In [46]:
# b) the sample variance of Batch 04 is
kombucha = pd.read_csv("datasets/kombucha.csv")
ksample08 = ... # select Batch 08 here

### Exercise 3.11

Compute the bootstrap approximation for sampling distribution of the variance
from Batch 08 of the kombucha dataset.
Plot a histogram.

In [48]:
kombucha = pd.read_csv("datasets/kombucha.csv")
ksample08 = ... # select Batch 08 here ...

kvars08_boot = ...

## Exercises 6


### Exercise 3.12

Describe the uncertainty about the difference between means `dmeans(scoresR,scoresU)`,
where `scoresR` and `scoresU` are sleep scores of the rural and urban doctors
from the doctors dataset `datasets/doctors.csv`.  
**a)** Find an analytical formula in terms Student's $t$ -distribution.  
**b)** Use bootstrap estimation.  
**c)** Compare your answers from part a) and b) graphically.

In [50]:
doctors = pd.read_csv("datasets/doctors.csv")
scoresR = doctors[doctors["loc"]=="rur"]["score"]
scoresU = doctors[doctors["loc"]=="urb"]["score"]

# observed value
dscores = dmeans(scoresR, scoresU)
dscores

6.992885375494076

In [51]:
# a) analytical approximation

# obtain the sample sizes and stds of the two groups
...

# compute standard error of the difference between group means
...

# calculate the degrees of freedom
from ministats import calcdf
...

# probability model based on Student's t-distribution
from scipy.stats import t as tdist
...

Ellipsis

In [53]:
# b) bootstrap estimate
# compute bootstrap estimates for mean in each group
meanR_boot = ... 
meanU_boot = ...

# compute the difference between means of bootstrap samples
dmeans_boot = ...

In [55]:
# c) plot the answers form a) and b)

# pdf of the analytical approximation 
...

# histogtam of the bootstrap approximation
...

Ellipsis

## Exercises 7


### Exercise 3.13

Generate the sampling distribution of the median for samples of size $n=30$ from the population `rvK` $= K \sim \mathcal{N}(1000,10)$ .

In [57]:
from scipy.stats import norm
rvK = norm(1000, 10)

# compute the sampling distribution of the median
# for samples of size n=30 from rvK
kmedians30 = ...

In [59]:
# compute se of the sampling distribution of the median
...

Ellipsis

### Exercise 3.14

Generate the sampling distribution of `P90` , the 90th percentile estimator,
from samples of size $n=30$ from `rvK`  $= K \sim \mathcal{N}(1000,10)$ .
Calculate the standard error $\stderr{\tt{P90}}$ of the estimator.

In [61]:
from scipy.stats import norm
rvK = norm(1000, 10)

In [62]:
# 90th percentile estimator function
def p90(sample):
    ...

# simulations of p90 from samples of size n=30
kp90s30 = gen_sampling_dist(rvK, estfunc=p90, n=30)

# histogram
...

Ellipsis

In [64]:
# compute se of the kp90s30 sampling distribution
...

Ellipsis

### Exercise 3.16

Use the function `scipy.stats.boostrap` to compute the bootstrap distribution
of the variance from the sample `ksample02`.

In [66]:
from scipy.stats import bootstrap

kombucha = pd.read_csv("datasets/kombucha.csv")
ksample02 = ...  # select Batch 02 here...

# call the function bootstrap
...

# plot histogram
...

Ellipsis