In [1]:
import random
import pandas as pd
import numpy as np
from scipy.stats.distributions import norm

### Data melt operation

In [2]:
random.seed(16)

nstudents = 7

grades_data = {
    "student_ID": (100 + np.arange(1, nstudents+1)).astype(int),
    "name": ["Amelie", "Franklin", "Marge", "Gab", "Caroline", "Nora", "Saul"],
    "test1": norm.rvs(60, 10, size=nstudents).round(0).astype(int),
    "test2": norm.rvs(70, 10, size=nstudents).round(0).astype(int),
    "test3": norm.rvs(80, 10, size=nstudents).round(0).astype(int),
}

markswide = pd.DataFrame(grades_data)
markswide

   student_ID      name  test1  test2  test3
0         101    Amelie     74     72     68
1         102  Franklin     62     58     92
2         103     Marge     74     62     83
3         104       Gab     66     78     67
4         105  Caroline     67     66     63
5         106      Nora     72     62     83
6         107      Saul     53     76     92

In [3]:
markswide.to_csv("../datasets/markswide.csv", index=False)

In [4]:
markswide2 = pd.read_csv("../datasets/markswide.csv")
markswide2.equals(markswide)

True

In [5]:
markswide.melt(id_vars=["student_ID", "name"], var_name="test", value_name="grade") \
         .replace({"test":{"test1":1, "test2":2, "test3":3}})

    student_ID      name test  grade
0          101    Amelie    1     74
1          102  Franklin    1     62
2          103     Marge    1     74
3          104       Gab    1     66
4          105  Caroline    1     67
5          106      Nora    1     72
6          107      Saul    1     53
7          101    Amelie    2     72
8          102  Franklin    2     58
9          103     Marge    2     62
10         104       Gab    2     78
11         105  Caroline    2     66
12         106      Nora    2     62
13         107      Saul    2     76
14         101    Amelie    3     68
15         102  Franklin    3     92
16         103     Marge    3     83
17         104       Gab    3     67
18         105  Caroline    3     63
19         106      Nora    3     83
20         107      Saul    3     92